"""Generates a complete, downloadable PDF report of a Construction
Studio design: plot/room summary, cost broken down by discipline,
Vastu/Thai compliance, and a schematic diagram + labeled element table
for each of Structural/Plumbing/Electrical, per floor.

Reuses the app's own existing computation modules rather than
recomputing or re-deriving anything: `design_disciplines.py` for the
cost-by-discipline grouping, `discipline_overlays.py` for the schematic
element placement (same labels/specs/legend the in-app view uses),
`compliance_rules.py` for the Vastu/Thai rule summary. This module's
own job is purely to lay all of that out on a page — it introduces no
new numbers of its own.

Carries forward the same critical honesty boundary as every module it
draws from: the schematic diagrams and their reference specs are a
visualization/planning aid, not a licensed engineer's calculated
design. The report's cover page and every discipline section restate
this — never state it once and let a later section imply otherwise.
"""

import io
from datetime import datetime, timezone
from typing import Any

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table,
)
from reportlab.graphics.shapes import Drawing, Rect, Line, Circle, String

from backend.design_disciplines import group_by_discipline
from backend.discipline_overlays import (
    compute_structural_overlay, compute_plumbing_overlay, compute_electrical_overlay,
)
from backend.compliance_rules import get_vastu_rules, get_thai_rules

_STYLES = getSampleStyleSheet()
_TITLE_STYLE = ParagraphStyle("ReportTitle", parent=_STYLES["Title"], fontSize=22, spaceAfter=6)
_SUBTITLE_STYLE = ParagraphStyle("ReportSubtitle", parent=_STYLES["Normal"], fontSize=11, textColor=HexColor("#6b5f85"))
_H1_STYLE = ParagraphStyle("H1", parent=_STYLES["Heading1"], fontSize=15, spaceBefore=14, spaceAfter=6, textColor=HexColor("#2c1f47"))
_H2_STYLE = ParagraphStyle("H2", parent=_STYLES["Heading2"], fontSize=12, spaceBefore=10, spaceAfter=4, textColor=HexColor("#4c1d95"))
_BODY_STYLE = ParagraphStyle("Body", parent=_STYLES["Normal"], fontSize=9.5, leading=13)
_DISCLAIMER_STYLE = ParagraphStyle(
    "Disclaimer", parent=_STYLES["Normal"], fontSize=8.5, leading=12,
    textColor=HexColor("#9a3412"), backColor=HexColor("#fff7ed"), borderPadding=8,
)
_SPEC_STYLE = ParagraphStyle("Spec", parent=_STYLES["Normal"], fontSize=7.5, leading=10)

_TABLE_HEADER_STYLE = [
    ("BACKGROUND", (0, 0), (-1, 0), HexColor("#faf7ff")),
    ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#4c1d95")),
    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ("FONTSIZE", (0, 0), (-1, -1), 8.5),
    ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#ede4fc")),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ("TOPPADDING", (0, 0), (-1, -1), 4),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
]

_TOP_LEVEL_DISCLAIMER = (
    "This report includes schematic Structural, Plumbing, and Electrical diagrams and reference "
    "dimensions generated by PropertyIQ for planning and visualization purposes. These are NOT a "
    "licensed engineer's calculated design. Real structural sizing depends on actual loads, soil "
    "bearing capacity, and seismic zone; real plumbing/electrical design depends on actual fixture "
    "counts, load calculations, and local code — none of which this report can know. Have a licensed "
    "structural engineer, plumber, and electrician review this design before construction."
)


def _legend_color(legend: list[dict[str, Any]], key: str) -> str:
    return next((e["color"] for e in legend if e["key"] == key), "#6b7280")


def _flip_y(y: float, width_ft: float) -> float:
    return width_ft - y


def _draw_structural_diagram(overlay: dict[str, Any], plot_length_ft: float, plot_width_ft: float) -> Drawing:
    """Native reportlab drawing — not an SVG conversion — using the same
    x/y feet coordinates discipline_overlays.py already computed, scaled
    to fit a fixed-size drawing area. Colors come from overlay['legend'],
    the same single source of truth the in-app view reads from."""
    scale = min(440 / plot_length_ft, 280 / plot_width_ft)
    d = Drawing(plot_length_ft * scale + 20, plot_width_ft * scale + 20)

    for wall in overlay["walls"]:
        color = _legend_color(overlay["legend"], "perimeter_wall" if wall["kind"] == "perimeter" else "partition_wall")
        x = wall["x"] * scale + 10
        y = _flip_y(wall["y"] + wall["width"], plot_width_ft) * scale + 10
        d.add(Rect(x, y, wall["length"] * scale, wall["width"] * scale, fillColor=None, strokeColor=HexColor(color), strokeWidth=1))

    beam_color = _legend_color(overlay["legend"], "beam")
    for beam in overlay["beams"]:
        d.add(Line(
            beam["x"] * scale + 10, _flip_y(beam["y"], plot_width_ft) * scale + 10,
            beam["x2"] * scale + 10, _flip_y(beam["y2"], plot_width_ft) * scale + 10,
            strokeColor=HexColor(beam_color), strokeWidth=1, strokeDashArray=[3, 2],
        ))

    col_color = _legend_color(overlay["legend"], "column")
    for col in overlay["columns"]:
        cx = col["x"] * scale + 10
        cy = _flip_y(col["y"], plot_width_ft) * scale + 10
        d.add(Rect(cx - 3, cy - 3, 6, 6, fillColor=HexColor(col_color), strokeColor=None))
        d.add(String(cx + 4, cy + 2, col["label"], fontSize=6, fillColor=HexColor("#1f2937")))

    return d


def _draw_plumbing_diagram(overlay: dict[str, Any], plot_length_ft: float, plot_width_ft: float) -> Drawing:
    scale = min(440 / plot_length_ft, 280 / plot_width_ft)
    d = Drawing(plot_length_ft * scale + 20, plot_width_ft * scale + 20)

    d.add(Rect(10, 10, plot_length_ft * scale, plot_width_ft * scale, fillColor=None, strokeColor=HexColor("#c4b5fd"), strokeWidth=0.5))

    pipe_color = _legend_color(overlay["legend"], "pipe_run")
    for run in overlay["pipe_runs"]:
        d.add(Line(
            run["from"]["x"] * scale + 10, _flip_y(run["from"]["y"], plot_width_ft) * scale + 10,
            run["to"]["x"] * scale + 10, _flip_y(run["to"]["y"], plot_width_ft) * scale + 10,
            strokeColor=HexColor(pipe_color), strokeWidth=1, strokeDashArray=[3, 2],
        ))

    fixture_color = _legend_color(overlay["legend"], "fixture")
    for f in overlay["fixtures"]:
        cx, cy = f["x"] * scale + 10, _flip_y(f["y"], plot_width_ft) * scale + 10
        d.add(Circle(cx, cy, 3, fillColor=HexColor(fixture_color), strokeColor=None))
        d.add(String(cx + 4, cy + 2, f["label"], fontSize=6, fillColor=HexColor("#1f2937")))

    if overlay["main_riser"]:
        riser = overlay["main_riser"]
        riser_color = _legend_color(overlay["legend"], "main_riser")
        cx, cy = riser["x"] * scale + 10, _flip_y(riser["y"], plot_width_ft) * scale + 10
        d.add(Rect(cx - 3.5, cy - 3.5, 7, 7, fillColor=HexColor(riser_color), strokeColor=None))
        d.add(String(cx + 4, cy + 2, riser["label"], fontSize=6, fillColor=HexColor("#1f2937")))

    return d


def _draw_electrical_diagram(overlay: dict[str, Any], plot_length_ft: float, plot_width_ft: float) -> Drawing:
    scale = min(440 / plot_length_ft, 280 / plot_width_ft)
    d = Drawing(plot_length_ft * scale + 20, plot_width_ft * scale + 20)

    d.add(Rect(10, 10, plot_length_ft * scale, plot_width_ft * scale, fillColor=None, strokeColor=HexColor("#c4b5fd"), strokeWidth=0.5))

    socket_color = _legend_color(overlay["legend"], "socket")
    for s in overlay["sockets"]:
        cx, cy = s["x"] * scale + 10, _flip_y(s["y"], plot_width_ft) * scale + 10
        d.add(Rect(cx - 2, cy - 2, 4, 4, fillColor=HexColor(socket_color), strokeColor=None))
        d.add(String(cx + 3, cy + 2, s["label"], fontSize=5.5, fillColor=HexColor("#1f2937")))

    switch_color = _legend_color(overlay["legend"], "switch")
    for s in overlay["switches"]:
        cx, cy = s["x"] * scale + 10, _flip_y(s["y"], plot_width_ft) * scale + 10
        d.add(Rect(cx - 2.5, cy - 2.5, 5, 5, fillColor=HexColor(switch_color), strokeColor=None))
        d.add(String(cx + 3, cy + 2, s["label"], fontSize=5.5, fillColor=HexColor("#1f2937")))

    fan_color = _legend_color(overlay["legend"], "fan")
    for f in overlay["fans"]:
        cx, cy = f["x"] * scale + 10, _flip_y(f["y"], plot_width_ft) * scale + 10
        d.add(Circle(cx, cy, 3.5, fillColor=None, strokeColor=HexColor(fan_color), strokeWidth=0.75))
        d.add(String(cx + 4, cy + 2, f["label"], fontSize=5.5, fillColor=HexColor("#1f2937")))

    light_color = _legend_color(overlay["legend"], "light")
    for l in overlay["lights"]:
        cx, cy = l["x"] * scale + 10, _flip_y(l["y"], plot_width_ft) * scale + 10
        d.add(Circle(cx, cy, 2.2, fillColor=None, strokeColor=HexColor(light_color), strokeWidth=0.75))
        d.add(String(cx + 3, cy + 2, l["label"], fontSize=5.5, fillColor=HexColor("#1f2937")))

    return d


def _legend_flowable(legend: list[dict[str, Any]]) -> Table:
    cells = []
    row = []
    for entry in legend:
        swatch = Drawing(10, 10)
        swatch.add(Rect(0, 0, 10, 10, fillColor=HexColor(entry["color"]), strokeColor=None))
        row.append(Table([[swatch, Paragraph(entry["label"], _BODY_STYLE)]], colWidths=[14, 110], style=[("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
    cells.append(row)
    return Table(cells, style=[("LEFTPADDING", (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (-1, -1), 10)])


def _elements_spec_table(elements: list[dict[str, Any]]) -> Table:
    rows = [["Label", "Reference Spec"]]
    for el in elements:
        rows.append([el["label"], Paragraph(el["spec"], _SPEC_STYLE)])
    return Table(rows, colWidths=[45, 460], style=_TABLE_HEADER_STYLE)


def generate_construction_report_pdf(
    design: dict[str, Any],
    floors: list[dict[str, Any]],
    property_name: str = "",
) -> bytes:
    """`design` is the saved design dict from construction_store.get_design
    (plot_spec, selections, cost_estimate, vastu_result, risks). `floors`
    is [{"floor_label": str, "rooms": [...]}, ...] — supplied separately
    since room layout isn't persisted with the saved design (see this
    module's own docstring)."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.6 * inch, bottomMargin=0.6 * inch, leftMargin=0.6 * inch, rightMargin=0.6 * inch)
    story = []

    plot_spec = design["plot_spec"]
    currency = design.get("currency", "USD")
    generated_at = datetime.now(timezone.utc).strftime("%d %b %Y")

    # --- Cover ---
    story.append(Paragraph(property_name or "Construction Studio Report", _TITLE_STYLE))
    story.append(Paragraph(f"Generated {generated_at} · PropertyIQ Construction Studio", _SUBTITLE_STYLE))
    story.append(Spacer(1, 14))
    story.append(Paragraph(_TOP_LEVEL_DISCLAIMER, _DISCLAIMER_STYLE))
    story.append(Spacer(1, 16))

    story.append(Paragraph("Plot Summary", _H1_STYLE))
    plot_rows = [
        ["Plot size", f"{plot_spec.get('plot_length_ft', '-')} ft × {plot_spec.get('plot_width_ft', '-')} ft"],
        ["Entrance direction", str(plot_spec.get("entrance_direction", "-")).title()],
        ["Road-facing side", str(plot_spec.get("road_facing_side", "-")).title()],
        ["Region", str(design.get("region", "-")).title()],
    ]
    story.append(Table(plot_rows, colWidths=[160, 340], style=_TABLE_HEADER_STYLE))

    # --- Room summary, per floor ---
    story.append(Paragraph("Room Layout", _H1_STYLE))
    for floor in floors:
        rooms = [r for r in floor.get("rooms", []) if r.get("name", "").strip() and r.get("length", 0) > 0 and r.get("width", 0) > 0]
        story.append(Paragraph(floor.get("floor_label", "Floor"), _H2_STYLE))
        if not rooms:
            story.append(Paragraph("No named rooms on this floor.", _BODY_STYLE))
            continue
        room_rows = [["Room", "Dimensions", "Area (sq ft)"]]
        for r in rooms:
            room_rows.append([r["name"], f"{r['length']:.0f}' × {r['width']:.0f}'", f"{r['length'] * r['width']:.0f}"])
        story.append(Table(room_rows, colWidths=[220, 140, 140], style=_TABLE_HEADER_STYLE))
        story.append(Spacer(1, 6))

    # --- Cost by discipline ---
    story.append(PageBreak())
    story.append(Paragraph("Cost Estimate by Discipline", _H1_STYLE))
    story.append(Paragraph(f"Total: {currency} {design['cost_estimate'].get('grand_total_converted', 0):,.0f}", _H2_STYLE))
    sections = group_by_discipline(design["cost_estimate"].get("line_items", []))
    for section in sections:
        story.append(Paragraph(f"{section['label']} — {currency} {section['subtotal_converted']:,.0f}", _H2_STYLE))
        item_rows = [["Item", "Cost"]]
        for item in section["line_items"]:
            tag = " (Labor)" if item.get("kind") == "labor" else ""
            item_rows.append([item["name"] + tag, f"{currency} {item['line_total_converted']:,.0f}"])
        story.append(Table(item_rows, colWidths=[380, 120], style=_TABLE_HEADER_STYLE))
        story.append(Spacer(1, 6))

    # --- Compliance ---
    story.append(PageBreak())
    vastu_result = design.get("vastu_result")
    if vastu_result and vastu_result.get("scope") != "no_specific_tradition":
        is_thai = str(vastu_result.get("scope", "")).startswith("thai_")
        story.append(Paragraph("Traditional Building Compliance" if is_thai else "Vastu Compliance", _H1_STYLE))
        story.append(Paragraph(f"Result: {'Compliant' if vastu_result.get('compliant') else 'Some items flagged'}", _H2_STYLE))
        for note in vastu_result.get("notes", []):
            text = note if isinstance(note, str) else note.get("text", "")
            story.append(Paragraph(f"• {text}", _BODY_STYLE))
        story.append(Spacer(1, 8))
        rules = get_thai_rules() if is_thai else get_vastu_rules()
        story.append(Paragraph("Rules checked:", _H2_STYLE))
        story.append(Paragraph(rules["scope_note"], _DISCLAIMER_STYLE))
        for rule in rules["rules"]:
            story.append(Paragraph(f"<b>{rule['title']}</b> — {rule['detail']}", _BODY_STYLE))

    # --- Structural / Plumbing / Electrical, per floor ---
    for floor in floors:
        rooms = floor.get("rooms", [])
        plot_length_ft = plot_spec.get("plot_length_ft", 1)
        plot_width_ft = plot_spec.get("plot_width_ft", 1)

        story.append(PageBreak())
        story.append(Paragraph(f"{floor.get('floor_label', 'Floor')} — Structural", _H1_STYLE))
        structural = compute_structural_overlay(rooms, plot_length_ft, plot_width_ft, total_floors=len(floors))
        story.append(Paragraph(structural["disclaimer"], _DISCLAIMER_STYLE))
        story.append(Spacer(1, 6))
        story.append(_draw_structural_diagram(structural, plot_length_ft, plot_width_ft))
        story.append(Spacer(1, 6))
        story.append(_legend_flowable(structural["legend"]))
        story.append(Spacer(1, 8))
        story.append(Paragraph("Columns", _H2_STYLE))
        story.append(_elements_spec_table(structural["columns"]))
        story.append(Spacer(1, 6))
        story.append(Paragraph("Beams", _H2_STYLE))
        story.append(_elements_spec_table(structural["beams"]))

        story.append(PageBreak())
        story.append(Paragraph(f"{floor.get('floor_label', 'Floor')} — Plumbing", _H1_STYLE))
        plumbing = compute_plumbing_overlay(rooms, plot_length_ft, plot_width_ft)
        story.append(Paragraph(plumbing["disclaimer"], _DISCLAIMER_STYLE))
        story.append(Spacer(1, 6))
        story.append(_draw_plumbing_diagram(plumbing, plot_length_ft, plot_width_ft))
        story.append(Spacer(1, 6))
        story.append(_legend_flowable(plumbing["legend"]))
        story.append(Spacer(1, 8))
        if plumbing["fixtures"]:
            story.append(Paragraph("Fixtures", _H2_STYLE))
            story.append(_elements_spec_table(plumbing["fixtures"]))
            story.append(Spacer(1, 6))
            story.append(Paragraph("Main Riser", _H2_STYLE))
            story.append(_elements_spec_table([plumbing["main_riser"]]))
        else:
            story.append(Paragraph("No bathroom/kitchen/utility rooms on this floor — no plumbing fixtures placed.", _BODY_STYLE))

        story.append(PageBreak())
        story.append(Paragraph(f"{floor.get('floor_label', 'Floor')} — Electrical", _H1_STYLE))
        electrical = compute_electrical_overlay(rooms, plot_length_ft, plot_width_ft)
        story.append(Paragraph(electrical["disclaimer"], _DISCLAIMER_STYLE))
        story.append(Spacer(1, 6))
        story.append(_draw_electrical_diagram(electrical, plot_length_ft, plot_width_ft))
        story.append(Spacer(1, 6))
        story.append(_legend_flowable(electrical["legend"]))
        story.append(Spacer(1, 8))
        story.append(Paragraph("Lights", _H2_STYLE))
        story.append(_elements_spec_table(electrical["lights"]))
        story.append(Spacer(1, 6))
        story.append(Paragraph("Fans", _H2_STYLE))
        story.append(_elements_spec_table(electrical["fans"]))
        story.append(Spacer(1, 6))
        story.append(Paragraph("Switches", _H2_STYLE))
        story.append(_elements_spec_table(electrical["switches"]))
        story.append(Spacer(1, 6))
        story.append(Paragraph("Sockets", _H2_STYLE))
        story.append(_elements_spec_table(electrical["sockets"]))

    # --- Final disclaimer ---
    story.append(PageBreak())
    story.append(Paragraph("Important Notice", _H1_STYLE))
    story.append(Paragraph(_TOP_LEVEL_DISCLAIMER, _DISCLAIMER_STYLE))

    doc.build(story)
    return buffer.getvalue()
